config/routes.rb
DomainManager::Application.routes.draw do

  namespace :api  do
    namespace :v1 do
      resources :accounts
      resources :domains
    end
  end

  resources :accounts
  resources :domains
  root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :domains,
    inverse_of: :account,
  dependent: :destroy

end

app/models/domain.rb
require 'socket'

class Domain < ActiveRecord::Base
  validates_presence_of :hostname
  validates_uniqueness_of :hostname
  validates_presence_of :account_id
  validates_presence_of :ip_address

  belongs_to :account,
    inverse_of: :domains

  def self.get_ip(hostname)
    hostname = hostname.gsub(/http:\/\/+|www\.+|\//, '')
    Socket::getaddrinfo(hostname, 'www', nil, Socket::SOCK_STREAM)[0][3]
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def show
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.create(account_params)
    if @account.save
      redirect_to @account, notice: 'Account was saved'
    else
      render action: 'new'
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to accounts_url, notice: 'Account was updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    if @account.destroy
      redirect_to accounts_url, notice: 'Account was successfully deleted'
    end
  end

  private
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/api/v1/accounts_controller.rb
module API
  module V1
    class AccountsController < ApplicationController
      protect_from_forgery
      respond_to :html, :json

      def index
        @accounts = Account.all
        respond_with @accounts
      end

      def new
        @account = Account.new
      end

      def show
        @account = Account.find(params[:id])
        respond_with @account
      end

      def edit
        @account = Account.find(params[:id])
      end

      def create
        @account = Account.create(account_params)
        respond_with @account
      end

      def update
        @account = Account.update(account_params)
        respond_with @account
      end

      def destroy
        @account = Account.destroy(params[:id])
        respond_with @account
      end

      private
        def account_params
          params.require(:account).permit(:name)
        end
    end
  end
end

app/controllers/api/v1/domains_controller.rb
module API
  module V1
    class DomainsController < ApplicationController
      skip_before_filter  :verify_authenticity_token
      respond_to :html, :json

      def index
        @domains = Domain.all
        respond_with @domains
      end

      def new
        @domain = Domain.new
      end

      def show
        @domain = Domain.find(params[:id])
        respond_with @domain
      end

      def edit
        @domain = Domain.find(params[:id])
        respond_with @domain
      end

      def create
        ip = Domain.get_ip(domain_params[:hostname])
        new_params = domain_params.merge(ip_address: ip)
        respond_with Domain.create(new_params)
      end

      def update
        @domain = Domain.find(params[:id])
        ip = Domain.get_ip(@domain.hostname)
        new_params = domain_params.merge(ip_address: ip)

        respond_with Domain.update(new_params)
      end

      def destroy
        @domain = Domain.find(params[:id])
        respond_with @domain.destroy
      end

      private
        def domain_params
          params.require(:domain).permit(:hostname, :ip_address, :account_id)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
  end

  def new
    @domain = Domain.new
  end

  def show
    @domain = Domain.find(params[:id])
  end

  def create
    ip = Domain.get_ip(domain_params[:hostname])
    new_params = domain_params.merge(ip_address: ip)
    @domain = Domain.create(new_params)
    if @domain.save
      redirect_to @domain, notice: 'Domain was saved'
    else
      render action: 'new'
    end
  end

  def edit
    @domain = Domain.find(params[:id])
  end

  def update
    @domain = Domain.find(params[:id])
    ip = Domain.get_ip(@domain.hostname)
    new_params = domain_params.merge(ip_address: ip)

    if @domain.update(new_params)
      redirect_to @domain, notice: 'Domain was updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @domain = Domain.find(params[:id])
    if @doman.destroy
      redirect_to domains_url, notice: 'Domain was successfully deleted'
    end
  end

  private
    def domain_params
      params.require(:domain).permit(:hostname, :ip_address, :account_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@account.errors.count, "error") %>
      prohibited this account from being saved:
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :name %>
    <%= f.submit %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>
<%= render 'form' %>

app/views/accounts/index.html.erb
<h1>All Accounts</h1>
<%= link_to 'Add Account', new_account_path %>
<br/><br/>
<table cellpadding='5' cellspacing='0' border='0'>
  <tr>
    <th>Name</th>
    <th>&nbsp;</th>
  </tr>
  <% @accounts.each do |account| %>
  <tr>
      <td><%= account.name %></td>
      <td><%= link_to 'Edit', edit_account_path(account) %> | <%= link_to 'Delete', account, method: :delete %></td>
  </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>
<%= render 'form' %>

app/views/accounts/show.html.erb
Name: <%= @account.name %><br/><br/>
<%= link_to 'Back', accounts_path %>

app/views/domains/_form.html.erb
<%= simple_form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@domain.errors.count, "error") %>
      prohibited this domain from being saved:
      <ul>
        <% @domain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :hostname %>
    <%= f.association :account %>
    <%= f.submit %>
<% end %>

app/views/domains/edit.html.erb
<h1>Edit Domain</h1>
<%= render 'form' %>

app/views/domains/index.html.erb
<h1>All Domains</h1>
<%= link_to 'Add Domain', new_domain_path %>
<br/><br/>
<table cellpadding='5' cellspacing='0' border='0'>
  <tr>
    <th>Hostname</th>
    <th>IP Address</th>
    <th>Account</th>
    <th>&nbsp;</th>
  </tr>
  <% @domains.each do |domain| %>
    <tr>
      <td><%= domain.hostname %></td>
      <td><%= domain.ip_address %></td>
      <td><%= domain.account.name %></td>
      <td><%= link_to 'Edit', edit_domain_path(domain) %> | <%= link_to 'Delete', domain, method: :delete %></td>
    </tr>
  <% end %>

</table>

app/views/domains/new.html.erb
<h1>New Domain</h1>
<%= render 'form' %>

app/views/domains/show.html.erb
Hostname: <%= @domain.hostname %><br/>
IP Address: <%= @domain.ip_address %><br/>
Account: <%= @domain.account.name %><br/><br/>

<%= link_to 'Back', domains_url %>

app/views/home/index.html.erb
<h1>Welcome to Domain Manager</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DomainManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
    <li><%= link_to 'Accounts', api_v1_accounts_path %></li>
    <li><%= link_to 'Domains', api_v1_domains_path %></li>
</nav>
<%= yield %>

</body>
</html>